const SET_PRODUCTOS = 'SET_PRODUCTOS';
const SET_IS_LOADING_PRODUCTOS = 'SET_IS_LOADING_PRODUCTosS';
const SET_ERROR_PRODUCTOS = 'SET_ERROR_PRODUCTOS';
const CLEAR_ERROR_PRODUCTOS = 'CLEAR_ERROR_PRODUCTOS';
const CLEAR_ALL_PRODUCTOS = 'CLEAR_ALL_PRODUCTOS';

export {
    SET_PRODUCTOS,
    SET_IS_LOADING_PRODUCTOS,
    SET_ERROR_PRODUCTOS,
    CLEAR_ERROR_PRODUCTOS,
    CLEAR_ALL_PRODUCTOS,
};
